# Generated by Django 6.0.1 on 2026-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Retired", "Retired"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
